### ISSUE TITLE
Error loading Preference Bundle on iOS 12.5.7

### ISSUE THREAD

**Issue by jalsco** [liberatoaguilar/DontSwipe#2]
Error messages show up in Settings. Result is that no setting options are visible and DontSwipe does not start running. 

I am very familiar with DontSwipe. It is one of my favorite tweaks ! Thank you for making it ✅🙏🏻 I used DontSwipe without any problem for a couple years on my 11ProMax running iOS 14 (jb by unc0ver ). Early in 2024 I upgraded to 12 ProMax running iOS 15.4 (jb by Dopamine) and I really WISH Don'tSwipe is available for that, but sadly it is not 😥

The current problem - to keep kids occupied on long travel I setup a bunch of videos on a iPad Mini2 (A7 processor, iOS 12.5.7, jb by Chimera ). I need to stop the kids touching the screen and changing whats running - so I installed DontSwipe 1.2-3 - from Sileo. It says supports ios 11.1.2 - 13.6. The installation was successful with no errors or messages. Activator is correctly installed and shows in Settings, as it should...

The problem is - even after a few resprings and a few re-installs the DontSwipe app does show in Settings BUT only with a message "There was an error loading the Preferences Bundle for DontSwipe".

I really hoping and praying 🙏🏻 there is an quick fix, or patch possible - or some other way to fix this... and can be done in the coming days (before my long travel with v young kids). 

As I wrote - DontSwipe is a super useful tweak, and I thank you 😊 for all the use I already got from it, on my other device.

Am really begging, that you @liberatoaguilar could please just take a look at this problem 🙏🏻🙏🏻 
Even any comments from you may be helpful. Maybe it can be fixed without code changes 🤷🏻‍♂️ I just do not know... 

![353379532-07fbb90f-9d03-4be6-a341-c89aab787a15](https://github.com/user-attachments/assets/0480e7b3-167d-4b19-8c88-7f1abe6e4c09)

**Comment by liberatoaguilar** [comment]
Hey, I am glad you are enjoying DontSwipe! Unfortunately I do not own a jailbroken device currently and I have no way to keep developing the tweak or debug this issue. One thing I can suggest is editing the preference bundle directly by using a file explorer. Look in /var/mobile/Library/Preferences/ or a similar path. Check out [this discussion](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://iosgods.com/topic/1013-tutorial-how-to-fix-failed-to-load-preference-bundle-for-x-error/&ved=2ahUKEwi-8MrSydKHAxW_L9AFHR4FDuQQFnoECDEQAQ&usg=AOvVaw2RDBqwG0xqX87wKntY7TGv) for more reference. Also be sure to search Reddit or anywhere else online on how to edit tweak plist files.

**Comment by jalsco** [comment]
Okay - thanks 🙏🏻 Yes, I am familiar on how to edit plists.  
That link is saying to take a copy from one place, and store (overwrite) into `/Library/PreferenceLoader/Preferences/ ` with no actual edits.  I hope I understood correctly . I will try within next 30 mins 😊😊😊🙏🏻

**Comment by jalsco** [comment]
`/Library/PreferenceBundles/DontSwipe.bundle/`  has 2 `plist` . 
They are `Info.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>DontSwipe</string>
	<key>CFBundleIdentifier</key>
	<string>com.secondeight.dontswipe</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>NSPrincipalClass</key>
	<string>xxxRootListController</string>
</dict>
</plist>
```

And   `Root.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>items</key>
	<array>
		<dict>
			<key>cellClass</key>
			<string>SRSwitchTableCell</string>
			<key>default</key>
			<true/>
			<key>defaults</key>
			<string>com.secondeight.dontswipe</string>
			<key>key</key>
			<string>AwesomeSwitch1</string>
			<key>label</key>
			<string>Enable Border</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSGroupCell</string>
			<key>footerText</key>
			<string>Disables notifications when DontSwipe is active.</string>
		</dict>
		<dict>
			<key>cellClass</key>
			<string>SRSwitchTableCell</string>
			<key>default</key>
			<true/>
			<key>defaults</key>
			<string>com.secondeight.dontswipe</string>
			<key>key</key>
			<string>AwesomeSwitch2</string>
			<key>label</key>
			<string>Disable Notifications</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSGroupCell</string>
			<key>footerText</key>
			<string>When this setting is enabled user interactions with the app are allowed, but exiting the app is still disabled.</string>
		</dict>
		<dict>
			<key>cellClass</key>
			<string>SRSwitchTableCell</string>
			<key>default</key>
			<false/>
			<key>defaults</key>
			<string>com.secondeight.dontswipe</string>
			<key>key</key>
			<string>AwesomeSwitch3</string>
			<key>label</key>
			<string>Enable Swipes</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSGroupCell</string>
			<key>label</key>
			<string> </string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSButtonCell</string>
			<key>action</key>
			<string>respringboi</string>
			<key>label</key>
			<string>Respring</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSGroupCell</string>
			<key>label</key>
			<string>Social</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSButtonCell</string>
			<key>action</key>
			<string>emailMethod</string>
			<key>label</key>
			<string>Email Me</string>
			<key>icon</key>
			<string>gmail.png</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSButtonCell</string>
			<key>action</key>
			<string>contactMethod</string>
			<key>label</key>
			<string>@SecondEight1</string>
			<key>icon</key>
			<string>twitter.png</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSButtonCell</string>
			<key>action</key>
			<string>donationMethod</string>
			<key>label</key>
			<string>Buy me a coffee?</string>
			<key>icon</key>
			<string>paypal.png</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSGroupCell</string>
			<key>label</key>
			<string>Version 1.2</string>
		</dict>
		<dict>
			<key>cell</key>
			<string>PSGroupCell</string>
			<key>footerText</key>
			<string>© 2018 Liberato Aguilar/SecondEight1</string>
		</dict>
	</array>
	<key>title</key>
	<string>DontSwipe</string>
</dict>
</plist>
```
In the Loader directory, has `/Library/PreferenceLoader/Preferences/DontSwipe.plist` 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>entry</key>
	<dict>
		<key>bundle</key>
		<string>DontSwipe</string>
		<key>cell</key>
		<string>PSLinkCell</string>
		<key>detail</key>
		<string>xxxRootListController</string>
		<key>icon</key>
		<string>icon.png</string>
		<key>isController</key>
		<true/>
		<key>label</key>
		<string>DontSwipe</string>
	</dict>
</dict>
</plist>
```

**Can you see anything obvious to EDIT or copy/change overwrite, in any of those  ??**

**Comment by jalsco** [comment]
I am thinking need change in makefile, change `ARCH = arm64e` to `ARCH = arm64e arm64`

But then ?  i am thinking need THEOS and Xcode, to rebuild ...  Oh dear 🤯😢

**Comment by jalsco** [comment]
I know you cannot test it, as you have no jailbroken device.

But could you please just re-run the `makefile` with `ARCH = arm64e arm64`  🙏🏻🙏🏻🙏🏻🙏🏻

Then, I will test it here. I believe we are so very very close .

Because it is an ipadmini2 👇👇 I think does not do `ARM64e`

```
Deltas-Mini2:~ root# neofetch
                    'c.          root@Deltas-Mini2
                 ,xNMM.          -----------------
               .OMMMMo           OS: iOS 12.5.7
               OMMM0,            Host: iPad mini 2
     .;loddo:' loolloddol;.      Kernel: 18.7.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 1 day, 20 hours, 31 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 272 (dpkg)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Terminal: /dev/ttys000
:MMMMMMMMMMMMMMMMMMMMMMMM:       CPU: Apple A7 (2) @ 1.4GHz
.MMMMMMMMMMMMMMMMMMMMMMMMX.      GPU: PowerVR G6430
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Memory: 607MiB / 972MiB
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.
    kMMMMMMMMMMMMMMMMMMMMMMd
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.

```
