### ISSUE TITLE
Using DontSwipe in rootless jb ( eg jb by Dopamine ) 

### ISSUE THREAD

**Issue by jalsco** [liberatoaguilar/DontSwipe#3]
https://github.com/haxi0/Derootifier/

This tool ☝ says it will convert old, non rootless tweaks for running on Dopamine (ie jailbroken ios 15 ) . 

Are there any concerns running DontSwipe thru that tool  ?? I am in semi transit at the moment, and will be able to access properly to try it myself, until a couple weeks. Just interested if you @liberatoaguilar have any comments or warnings, about using that approach ?

**Comment by liberatoaguilar** [comment]
I have not tested any of my tweaks with this tool, so I am not sure if they will work on a rootless jb. If you do end up trying it, be sure to update! Again, I am not familiar with the tool, so I would contact the developer for any potential risks.

**Comment by jalsco** [comment]
ok - I will try - as soon as I can. And I will update on here. TY so much for replying 🙏🏻
